#!/Users/mailund/anaconda/bin/python

import argparse

from gwf.parser import parse
from gwf.dependency_graph import DependencyGraph
from gwf.graphviz import print_graphviz

parser = argparse.ArgumentParser(description='Show a workflow graph.')

parser.add_argument('workflow_file', help='The .gwf file containing the workflow')

parser.add_argument('output', nargs='?', default='default.dot',
                    help='File to write the workflow graph to.')

args = parser.parse_args()

if args.output == 'default.dot':
    args.output = args.workflow_file + '.dot'
    

workflow = parse(args.workflow_file)
graph = DependencyGraph(workflow)

with open(args.output, 'w') as out:
    print_graphviz(graph, out)
