#!/usr/bin/env python

import sys
import argparse

from gwf.parser import parse
from gwf.task_scheduler import TaskScheduler

parser = argparse.ArgumentParser(description='Run a workflow locally.')

parser.add_argument('-f', '--file',
                    default='workflow.gwf', dest='workflow_file',
                    help='workflow file if not the default (workflow.gwf).')
parser.add_argument('targets', nargs='+',
                    help='the target(s) to process.')

args = parser.parse_args()

workflow = parse(args.workflow_file, args.targets)

for target in args.targets:
    if target not in workflow.targets:
        print 'Target %s not found in workflow.' % target
        sys.exit(2)

scheduler = TaskScheduler(workflow)
scheduler.run()
