#!/Users/mailund/anaconda/bin/python

# This is a simple script for testing if list transformations work as intended.
# It just prints all the lists in the workflow so the user can test that they are
# processed they way it was intended.

import os
import sys
from gwf2.parser import parse


import argparse

parser = argparse.ArgumentParser(description='Print processed lists.')

parser.add_argument('workflow_file', help='The .gwf file containing the workflow')

args = parser.parse_args()

workflow = parse(args.workflow_file)
for lst in workflow.lists.values():
    print lst
